CREATE PROC FI_SP_ConsBeneficiario
	@ID BIGINT = null,
	@IDCLIENTE BIGINT = null
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IDCLIENTE
	ELSE
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID
END